### PR TITLE
Fixes #503: Fix the camera opening on clicking the notification

### LINKED ISSUE #503: Camera opening on clicking the message push notification

### PR DESCRIPTION
**Pull request by kunall17**
So it seems the action in the intent from the notification has the action as null and its going to `dispatchTakePictureIntent();` as the filepath will be null as well, so the camera app is opening on pressing notification!

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

File: app/src/main/java/com/zulip/android/activities/ZulipActivity.java [hunk 1]
```diff
@@ -893,6 +894,8 @@ protected void onNewIntent(Intent intent) {
                 // photo was deleted and camera is launched again to capture a new photo
                 dispatchTakePictureIntent();
             }
+        } else if (action.equals(ACTION_MESSAGE_PUSH_NOTIFICATION)) {
```
Comment (kunall17) [inline app/src/main/java/com/zulip/android/activities/ZulipActivity.java]: I am aware this thing is not required, but lets have.
It would help the developers to use the intent if they want to!

File: app/src/main/java/com/zulip/android/activities/ZulipActivity.java [hunk 2]
```diff
@@ -893,6 +894,8 @@ protected void onNewIntent(Intent intent) {
...
+            //Do nothing here
```
Comment (timabbott) [inline app/src/main/java/com/zulip/android/activities/ZulipActivity.java]: explain in the comment why you should do nothing here.

File: app/src/main/java/com/zulip/android/activities/ZulipActivity.java (hunk 1 above)
Comment (Sam1301) [inline app/src/main/java/com/zulip/android/activities/ZulipActivity.java]: cool, structurally I think it might be better to handle this case in the preceding if-else as that is for discerning actions. Works well though 👍
