### PR TITLE
Fixes #287 Bug in textColor of EditText

### LINKED ISSUE #287: Small UI bug in textColor of EditText
**Actual Behaviour**
While searching for people in night theme, `textColor` of EditText is white by default:

giphy 1

**Expected Behaviour**

giphy

@timabbott @kunall17 Shall I make PR for this?

### PR DESCRIPTION
**Pull request by yadav-rahul**
This PR fixes #287.
 As this issue was only with dark theme hence it first check as if current theme is _dark_ or not. If yes, then it changes editText color to `colorPrimary` to macth with dark theme properly.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@yadav-rahul, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

File: app/src/main/java/com/zulip/android/activities/ZulipActivity.java [hunk 1]
```diff
@@ -172,6 +172,7 @@
     private AppBarLayout appBarLayout;
 
     private MutedTopics mMutedTopics;
+    private boolean isCurrentThemeNight;
```
Comment (kunall17) [inline app/src/main/java/com/zulip/android/activities/ZulipActivity.java]: Convert 'isCurrentThemeNight' to a local variable!

**Comment by yadav-rahul** [comment]
@kunall17 done :+1:

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@yadav-rahul, thanks for signing the CLA!

**Comment by kunall17** [comment]
After re-formating the whole project by bc5a25f the merge conflicts have been created, fix those!

**Comment by yadav-rahul** [comment]
OK. I will update this PR soon.

**Comment by yadav-rahul** [comment]
@kunall17 Merge conflicts resolved.

File: app/src/main/java/com/zulip/android/activities/ZulipActivity.java [hunk 2]
```diff
@@ -328,6 +329,10 @@ public void onClick(View v) {
             }
         });
         etSearchStream = (EditText) findViewById(R.id.stream_drawer_search);
+        if (isCurrentThemeNight) {
+            etSearchPeople.setTextColor(ContextCompat.getColor(this, R.color.colorPrimary));
```
Comment (Sam1301) [inline app/src/main/java/com/zulip/android/activities/ZulipActivity.java]: I was wondering why color primary. Can we use Color.WHITE here? 
If we change the primary color of our app in future, this may cause some trouble.

Comment (yadav-rahul) [inline app/src/main/java/com/zulip/android/activities/ZulipActivity.java]: @Sam1301 Color assigned to editText by default is white only (in black theme).But white Color was kind of invisible because of white Color of background of editText.

Yes it may cause some issue in near future if we change colourPrimary. To avoid this we can add new value in colors.xml.
@kunall17 What do you think about this?

Comment (kunall17) [inline app/src/main/java/com/zulip/android/activities/ZulipActivity.java]: Creating a new one seems better option!

Comment (yadav-rahul) [inline app/src/main/java/com/zulip/android/activities/ZulipActivity.java]: @kunall17 Done.

**Comment by kunall17** [comment]
Remove the ptch: in the commit message!

**Comment by yadav-rahul** [comment]
@kunall17 Done.

**Comment by kunall17** [comment]
@timabbott LGTM! :)

**Comment by timabbott** [comment]
Merged, thanks @yadav-rahul!!
